name: hooks
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  clipboard: ^0.1.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.1
  devicelocale: ^0.6.0
  dio: ^5.1.2
  equatable: ^2.0.5
  fast_gbk: ^1.0.0
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_fadein:
    git:
      url: https://github.com/holusojivhictor/flutter_fadein
      ref: master
  flutter_inappwebview: ^6.0.0-beta.23
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  fluttertoast: ^8.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^7.0.2
  html: ^0.15.3
  html_unescape: ^2.0.0
  http: ^0.13.6
  hydrated_bloc: ^9.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  linkify: ^5.0.0
  logger: ^1.3.0
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  pull_to_refresh: ^2.0.0
  responsive_builder: ^0.7.0
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  sembast: ^3.4.4
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  sprintf: ^7.0.0
  tuple: ^2.0.1
  url_launcher: ^6.1.11
  version_tracker:
    git:
      url: https://github.com/holusojivhictor/version_tracker
      ref: main

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Regular.ttf
        - asset: assets/fonts/ClashDisplay-Extralight.ttf
          weight: 200
        - asset: assets/fonts/ClashDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/ClashDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Bold.ttf
          weight: 700
